# Generated by Django 6.0.5 on 2026-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('wishlist', 'Quero Jogar'), ('playing', 'Jogando'), ('finished', 'Zerado'), ('dropped', 'Abandonado')], max_length=20)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField()),
                ('favorito', models.BooleanField(default=False)),
            ],
        ),
    ]
