# Generated by Django 6.0.5 on 2026-05-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Quero Jogar'), ('playing', 'Jogando'), ('finished', 'Zerado'), ('dropped', 'Abandonado')], default='wishlist', max_length=20),
        ),
    ]
