# Generated by Django 6.0.5 on 2026-05-16 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_data_lancamento_game_imagem_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='data_lancamento',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='game',
            name='plataforma',
        ),
        migrations.AlterField(
            model_name='game',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
