# Generated by Django 6.0.5 on 2026-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_data_lancamento_remove_game_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
